#!/usr/bin/env sh
set -exu

MY_DIR=$(dirname $(readlink -f $0))

. "${MY_DIR}/defaults.sh"
. "${MY_DIR}/activate.sh"

if test -d "${OPAM_ROOT_PATH}"; then
  eval `${OPAM} config -env`
  ${OPAM} switch "${OCAML_VERSION}"
  ${OPAM} update
else
  mkdir "${OPAM_ROOT_PATH}"
  ${OPAM} init incubaid "git://github.com/Incubaid/opam-repository.git"
  ${OPAM} remote -add incubaid-dev "git://github.com/Incubaid/opam-repository-devel.git"
  eval `${OPAM} config -env`
  ${OPAM} switch "${OCAML_VERSION}"
fi

${OPAM} --yes install ${DEPENDENCIES};
