#!/usr/bin/env sh
set -exu

MY_DIR=$(dirname $(readlink -f $0))

. "${MY_DIR}/defaults.sh"
. "${MY_DIR}/activate.sh"


# Clean up old build env so the artifacts have a clean destination
rm -Rf "${OPAM_ROOT}"

# Optionally remove everything OPAM installed.
if test "${RESET_OPAM}" = "true"; then
  rm -Rf "${OPAM_ROOT_PATH}"
fi
