#!/usr/bin/env sh
set -exu

. defaults.sh
. activate.sh

# Clean up old build env so the artifacts have a clean destination
rm -Rf "${OPAM_ROOT}"

# Optionally remove everything OPAM installed.
if test "${RESET_OPAM}" = "true"; then
  rm -Rf "${OPAM_ROOT_PATH}"
fi
